""" Python configuration files
It holds global variables"""

STUDENTS = []
PROJECT_AREAS = []
SUPERVISORS = {}
MAX_ITERATIONS = None
VELOCITY = None
EPSILON = 0.1
MUTATION_PROB = 0.1
CURRENT_ITERATION = 1
NUM_ITERATIONS = 500
NUM_AGENTS = 100
